import { SubtitleTrack, SubtitleCue, SubtitleStyle, SubtitleAnimation } from '../../types';

export class AssSerializer {
  /**
   * Serializes a SubtitleTrack into ASS format string.
   * @param track The SubtitleTrack to serialize.
   * @returns ASS formatted string.
   */
  public static serialize(track: SubtitleTrack): string {
    let output = '';

    // [Script Info]
    output += '[Script Info]\n';
    output += 'Title: Generated by @tasma/ffmpeg-core\n';
    output += 'ScriptType: v4.00+\n';
    output += 'WrapStyle: 0\n';
    output += 'ScaledBorderAndShadow: yes\n';
    output += 'YCbCr Matrix: None\n\n';

    // Extract unique styles or just define Default
    const defaultStyleStr = 'Style: Default,Arial,20,&H00FFFFFF&,&H000000FF&,&H00000000&,&H00000000&,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\n';
    
    // [V4+ Styles]
    output += '[V4+ Styles]\n';
    output += 'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\n';
    output += defaultStyleStr;
    
    // We can also generate a style per cue if needed, but inline tags are safer for localized overrides
    // Let's generate named styles for each unique style object to be clean, 
    // or just rely on inline tags. The prompt asks to map the color to ASS BGR.
    // Let's define a helper to map style object to inline ASS tags.
    
    // [Events]
    output += '\n[Events]\n';
    output += 'Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n';

    for (const cue of track.cues) {
      const start = this.formatTime(cue.startMs);
      const end = this.formatTime(cue.endMs);
      const styleName = 'Default';
      const animTag = this.getAnimationTag(cue.animation);
      const styleTags = this.getInlineStyleTags(cue.style);
      
      // text might have newlines, replace them with \N for ASS
      const safeText = cue.text.replace(/\r?\n/g, '\\N');
      
      const fullText = `${styleTags}${animTag}${safeText}`;
      
      // Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
      output += `Dialogue: 0,${start},${end},${styleName},,0,0,0,,${fullText}\n`;
    }

    return output;
  }

  private static formatTime(ms: number): string {
    const h = Math.floor(ms / 3600000);
    const m = Math.floor((ms % 3600000) / 60000);
    const s = Math.floor((ms % 60000) / 1000);
    const cs = Math.floor((ms % 1000) / 10);
    return `${h}:${m.toString().padStart(2, '0')}:${s.toString().padStart(2, '0')}.${cs.toString().padStart(2, '0')}`;
  }

  private static getAnimationTag(anim?: SubtitleAnimation): string {
    if (!anim) return '';
    if (anim.type === 'fade') {
      // Basic fade animation {\fad(t1,t2)}
      return `{\\fad(${anim.durationMs},${anim.durationMs})}`;
    }
    return '';
  }

  private static getInlineStyleTags(style?: SubtitleStyle): string {
    if (!style) return '';
    
    let tags = '';
    if (style.fontFamily) {
      tags += `\\fn${style.fontFamily}`;
    }
    if (style.fontSize) {
      tags += `\\fs${style.fontSize}`;
    }
    if (style.color) {
      tags += `\\c${this.hexToAssColor(style.color)}`;
    }
    if (style.alignment !== undefined) {
      tags += `\\an${style.alignment}`;
    }
    
    return tags ? `{${tags}}` : '';
  }

  private static hexToAssColor(hex: string): string {
    // Map SubtitleStyle colors (hex) into ASS BGR format (&HBBGGRR&)
    const cleanHex = hex.replace(/^#/, '');
    if (cleanHex.length === 6) {
      const r = cleanHex.substring(0, 2);
      const g = cleanHex.substring(2, 4);
      const b = cleanHex.substring(4, 6);
      return `&H${b}${g}${r}&`;
    }
    if (cleanHex.length === 8) {
      // If it contains alpha, AARRGGBB in hex or RRGGBBAA? 
      // Usually RRGGBB. Let's just grab the RGB part assuming it's RRGGBBAA.
      const r = cleanHex.substring(0, 2);
      const g = cleanHex.substring(2, 4);
      const b = cleanHex.substring(4, 6);
      return `&H${b}${g}${r}&`;
    }
    return '&H00FFFFFF&';
  }
}
